package com.wym.petshop.mapper;

import com.wym.petshop.model.Cart;
import com.wym.petshop.model.CartExample;
import com.wym.petshop.model.CartKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.mapping.StatementType;
import org.apache.ibatis.type.JdbcType;
import org.springframework.web.bind.annotation.RestController;

@RestController
public interface CartMapper {

    /**
     *  自定义存储过程
     */

     @Insert(value="{CALL addCart7("+
             "#{in_username, mode=IN, jdbcType=VARCHAR}," +
             "#{in_itemid, mode=IN, jdbcType=VARCHAR}," +
             "#{in_quantity, mode=IN, jdbcType=INTEGER}," +
             "#{out_oid, mode=OUT, jdbcType=INTEGER}" +
             ")}")
     @Options(statementType = StatementType.CALLABLE)//证明是存储过程
     int addCart(Map map);
    @Update(value = "{ call updateCart7(" +
            "#{in_username, mode=IN, jdbcType=VARCHAR}," +
            "#{in_itemid, mode=IN, jdbcType=VARCHAR}," +
            "#{in_quantity, mode=IN, jdbcType=INTEGER}," +
            "#{in_orderid, mode=IN, jdbcType=INTEGER}" +
            ")}")
    @Options(statementType = StatementType.CALLABLE)//我是存储过程
    int uptCart(Map map);
    @Insert(value = "{ call delCart7(" +
            "#{in_username, mode=IN, jdbcType=VARCHAR}," +
            "#{in_itemid, mode=IN, jdbcType=VARCHAR}," +
            "#{in_oid, mode=IN, jdbcType=INTEGER}" +
            ")}")
    @Options(statementType = StatementType.CALLABLE)//我是存储过程
    int delCart(Map map);

    @Select(value = "{ call queryCart7(" +
            "#{in_oid, mode=IN, jdbcType=INTEGER}," +
            "#{in_username, mode=IN, jdbcType=VARCHAR}" +
            ")}")
    @Results({
            @Result(column="orderid", property="orderid", jdbcType= JdbcType.INTEGER, id=true),
            @Result(column="itemid", property="itemid", jdbcType= JdbcType.VARCHAR, id=true),
            @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="quantity", property="quantity", jdbcType= JdbcType.INTEGER),
            @Result(column="itemid", property="item",
                    one=@One(select="com.wym.petshop.mapper.ItemMapper.findItemByItemid"))
    })
    @Options(statementType = StatementType.CALLABLE)//我是存储过程
    List<Cart> queryCart(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @SelectProvider(type=CartSqlProvider.class, method="countByExample")
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @DeleteProvider(type=CartSqlProvider.class, method="deleteByExample")
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @Delete({
        "delete from cart",
        "where orderid = #{orderid,jdbcType=INTEGER}",
          "and itemid = #{itemid,jdbcType=VARCHAR}",
          "and username = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(CartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @Insert({
        "insert into cart (orderid, itemid, ",
        "username, quantity)",
        "values (#{orderid,jdbcType=INTEGER}, #{itemid,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR}, #{quantity,jdbcType=INTEGER})"
    })
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @InsertProvider(type=CartSqlProvider.class, method="insertSelective")
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @SelectProvider(type=CartSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="orderid", property="orderid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="itemid", property="itemid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER)
    })
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @Select({
        "select",
        "orderid, itemid, username, quantity",
        "from cart",
        "where orderid = #{orderid,jdbcType=INTEGER}",
          "and itemid = #{itemid,jdbcType=VARCHAR}",
          "and username = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="orderid", property="orderid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="itemid", property="itemid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER)
    })
    Cart selectByPrimaryKey(CartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @UpdateProvider(type=CartSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @UpdateProvider(type=CartSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @UpdateProvider(type=CartSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    @Update({
        "update cart",
        "set quantity = #{quantity,jdbcType=INTEGER}",
        "where orderid = #{orderid,jdbcType=INTEGER}",
          "and itemid = #{itemid,jdbcType=VARCHAR}",
          "and username = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Cart record);
}