package com.wym.petshop.model;

public class CartKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.orderid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.itemid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.orderid
     *
     * @return the value of cart.orderid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.orderid
     *
     * @param orderid the value for cart.orderid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.itemid
     *
     * @return the value of cart.itemid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.itemid
     *
     * @param itemid the value for cart.itemid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.username
     *
     * @return the value of cart.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.username
     *
     * @param username the value for cart.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}