package com.wym.petshop.model;

import java.io.Serializable;

public class Cart extends CartKey implements Serializable{
    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    private Item item;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.quantity
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.quantity
     *
     * @return the value of cart.quantity
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.quantity
     *
     * @param quantity the value for cart.quantity
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}