package com.wym.petshop.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.catid
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    private String catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.descn
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.catid
     *
     * @return the value of category.catid
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public String getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.catid
     *
     * @param catid the value for category.catid
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public void setCatid(String catid) {
        this.catid = catid == null ? null : catid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.descn
     *
     * @return the value of category.descn
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.descn
     *
     * @param descn the value for category.descn
     *
     * @mbg.generated Mon Jun 25 22:12:14 CST 2018
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
}