package com.wym.petshop.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orders extends OrdersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderdate
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalprice
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private BigDecimal totalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderdate
     *
     * @return the value of orders.orderdate
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderdate
     *
     * @param orderdate the value for orders.orderdate
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalprice
     *
     * @return the value of orders.totalprice
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalprice
     *
     * @param totalprice the value for orders.totalprice
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }
}