package com.wym.petshop.model;

import java.io.Serializable;
import java.security.SecureRandom;

public class Profile implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.lang
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private String lang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.catid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    private String catid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.username
     *
     * @return the value of profile.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.username
     *
     * @param username the value for profile.username
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.lang
     *
     * @return the value of profile.lang
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.lang
     *
     * @param lang the value for profile.lang
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.catid
     *
     * @return the value of profile.catid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public String getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.catid
     *
     * @param catid the value for profile.catid
     *
     * @mbg.generated Mon Jun 25 22:12:15 CST 2018
     */
    public void setCatid(String catid) {
        this.catid = catid == null ? null : catid.trim();
    }
}